site_name: Traduction Club Documentation
site_description: Docs website.
site_author: Traduction Club!

repo_name: New-Traduction-Club/td-club-docs
repo_url: https://github.com/New-Traduction-Club/td-club-docs

theme:
  name: material
  
  logo: https://files.traduction-club.live/favicon.ico
  favicon: https://files.traduction-club.live/favicon.ico
  
  font:
    text: Roboto
    code: Fira Code
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Just Sayori:
    - Home: js/home.md
    - Custom Locations: js/Backgrounds-System.md
    - Coding Style: js/Coding-Style.md
    - Data Transfer: js/Data-Transfer.md
    - Gifting System: js/Gifting-System.md
    - Gifts (SPOILERS): js/Gifts-(SPOILERS).md
    - Installing the mod: js/Installing-the-mod.md
    - Minigames System: js/Minigame-Hub.md
    - Outfits: js/Outfits.md
    - Persistent Variables: js/Persistent-Variables.md
    - Submodding: js/Submodding.md
    - Submodding API Reference: js/Submod-API-Reference.md
  # - Monika After Story (ES):
  #   - Inicio: mas-es/Home.md
  #   - API Keys: mas-es/API-Keys.md
  #   - Adding Custom Backgrounds: mas-es/Adding-Custom-Backgrounds.md
  #   - Adding Custom Music: mas-es/Adding-Custom-Music.md
  #   - Adding Custom Piano Songs: mas-es/Adding-Custom-Piano-Songs.md
  #   - Adding Sprite Objects: mas-es/Adding-Sprite-Objects.md
  #   - All Features (SPOILERS): "mas-es/All-Features-[SPOILERS].md"
  #   - Code of Conduct: mas-es/Code-of-Conduct.md
  #   - Coding Style: mas-es/Coding-Style.md
  #   - Community Piano Songs: mas-es/Community-Piano-Songs.md
  #   - Contributing Guidelines: mas-es/Contributing-Guidelines.md
  #   - Contributing New Greetings: mas-es/Contributing-new-greetings.md
  #   - Credits: mas-es/Credits.md
  #   - Decorators: mas-es/Decorators.md
  #   - DelayedAction: mas-es/DelayedAction.md
  #   - Dialogue Coding: mas-es/Dialogue-Coding.md
  #   - External Content: mas-es/External-Content.md
  #   - FAQ: mas-es/FAQ.md
  #   - Frameworks: mas-es/Frameworks.md
  #   - Gift Giving Guide: mas-es/Gift-Giving-Guide.md
  #   - Init Pipeline: mas-es/Init-Pipeline.md
  #   - Installation and Readme: mas-es/Installation-and-Readme.md
  #   - Interfacing with the Submod Framework: mas-es/Interfacing-with-the-Submod-Framework.md
  #   - License and Team Salvato Guidelines: mas-es/License-and-Team-Salvato-Guidelines.md
  #   - Logs and Other Files: mas-es/Logs-and-Other-Files.md
  #   - NOU Rules: mas-es/NOU-rules.md
  #   - Official MAS Art PSDs and Guidelines: mas-es/Official-MAS-Art-PSDs-and-Guidelines.md
  #   - Player Variables for Dialogue Coding: mas-es/Player-Variables-for-Dialogue-Coding.md
  #   - Rules System: mas-es/Rules-System.md
  #   - Testing Flow and Bug Testing: mas-es/Testing-Flow-and-Bug-Testing.md
  #   - The Deco Framework for Backgrounds: mas-es/The-Deco-Framework-for-Backgrounds.md
  #   - Troubleshooting: mas-es/Troubleshooting.md
  #   - Using Parts of Monika After Story in Your Own Project: mas-es/Using-parts-of-Monika-After-Story-in-your-own-project.md
  - MASL 6.99:
    - Home: masl-sixsixnine/home.md
    - Virtual Desktop: masl-sixsixnine/Virtual-Desktop.md
    - Experiments: masl-sixsixnine/Experiments.md
    - Submods Compatibility: masl-sixsixnine/Submods-Compatibility.md
    - MAICA Compatibility: masl-sixsixnine/Maica.md
  - Just Natsuki Launcher (JNL):
    - Home: jnl/home.md
    - How to pass my progress from older JN port to JNL: jnl/How-to-pass-JN-progress.md
